## Red Neuronal coche con Keras y Tensorflow

#### Librerias

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense

2022-12-09 12:59:27.193980: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


#### Se cargan las entradas

In [2]:
datos_entrenamiento = np.array([[-1,0],[-1,1],[-1,-1],[0,-1],[0,1],[0,0],[1,1],[1,-1],[1,0]], "float32")

datos_entrenamiento

array([[-1.,  0.],
       [-1.,  1.],
       [-1., -1.],
       [ 0., -1.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 1., -1.],
       [ 1.,  0.]], dtype=float32)

#### Se cargan las salidas

In [3]:
datos_salida = np.array([[1,0,0,1],[1,0,0,1],[1,0,0,1],[0,1,0,1],[1,0,1,0],[1,0,0,1],[0,1,1,0],[0,1,1,0],[0,1,1,0]], "float32")

#### Se programa la Red Neuronal

In [6]:
model = Sequential()
model.add(Dense(18, input_dim=2, activation='relu'))
model.add(Dense(4, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['binary_accuracy'])

model.fit(datos_entrenamiento, datos_salida, epochs=200)

Epoch 1/200
1/1 [==============================] - 5s 5s/step - loss: 0.2734 - binary_accuracy: 0.4444
Epoch 2/200
1/1 [==============================] - 0s 20ms/step - loss: 0.2726 - binary_accuracy: 0.4722
Epoch 3/200
1/1 [==============================] - 0s 89ms/step - loss: 0.2719 - binary_accuracy: 0.4722
Epoch 4/200
1/1 [==============================] - 0s 26ms/step - loss: 0.2711 - binary_accuracy: 0.4722
Epoch 5/200
1/1 [==============================] - 0s 60ms/step - loss: 0.2703 - binary_accuracy: 0.4722
Epoch 6/200
1/1 [==============================] - 0s 31ms/step - loss: 0.2696 - binary_accuracy: 0.4722
Epoch 7/200
1/1 [==============================] - 0s 21ms/step - loss: 0.2688 - binary_accuracy: 0.4722
Epoch 8/200
1/1 [==============================] - 0s 22ms/step - loss: 0.2681 - binary_accuracy: 0.4722
Epoch 9/200
1/1 [==============================] - 0s 34ms/step - loss: 0.2673 - binary_accuracy: 0.4722
Epoch 10/200
1/1 [==============================] - 0s 72

#### Se evaluá el modelo

In [7]:
scores = model.evaluate(datos_entrenamiento, datos_salida)

print(model.metrics_names[1], scores[1]*100)
print(model.predict(datos_entrenamiento).round())

1/1 [==============================] - 0s 220ms/step - loss: 0.1355 - binary_accuracy: 0.9444
binary_accuracy 94.44444179534912
1/1 [==============================] - 0s 71ms/step
[[1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 1. 1.]
 [0. 1. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 0.]]
